/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ValidacaoRouteImport } from './routes/validacao'
import { Route as TransportesRouteImport } from './routes/transportes'
import { Route as SolicitarRouteImport } from './routes/solicitar'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as MotoristasRouteImport } from './routes/motoristas'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'

const ValidacaoRoute = ValidacaoRouteImport.update({
  id: '/validacao',
  path: '/validacao',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportesRoute = TransportesRouteImport.update({
  id: '/transportes',
  path: '/transportes',
  getParentRoute: () => rootRouteImport,
} as any)
const SolicitarRoute = SolicitarRouteImport.update({
  id: '/solicitar',
  path: '/solicitar',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const MotoristasRoute = MotoristasRouteImport.update({
  id: '/motoristas',
  path: '/motoristas',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/motoristas': typeof MotoristasRoute
  '/perfil': typeof PerfilRoute
  '/solicitar': typeof SolicitarRoute
  '/transportes': typeof TransportesRoute
  '/validacao': typeof ValidacaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/motoristas': typeof MotoristasRoute
  '/perfil': typeof PerfilRoute
  '/solicitar': typeof SolicitarRoute
  '/transportes': typeof TransportesRoute
  '/validacao': typeof ValidacaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/motoristas': typeof MotoristasRoute
  '/perfil': typeof PerfilRoute
  '/solicitar': typeof SolicitarRoute
  '/transportes': typeof TransportesRoute
  '/validacao': typeof ValidacaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/motoristas'
    | '/perfil'
    | '/solicitar'
    | '/transportes'
    | '/validacao'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/motoristas'
    | '/perfil'
    | '/solicitar'
    | '/transportes'
    | '/validacao'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/motoristas'
    | '/perfil'
    | '/solicitar'
    | '/transportes'
    | '/validacao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MotoristasRoute: typeof MotoristasRoute
  PerfilRoute: typeof PerfilRoute
  SolicitarRoute: typeof SolicitarRoute
  TransportesRoute: typeof TransportesRoute
  ValidacaoRoute: typeof ValidacaoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/validacao': {
      id: '/validacao'
      path: '/validacao'
      fullPath: '/validacao'
      preLoaderRoute: typeof ValidacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transportes': {
      id: '/transportes'
      path: '/transportes'
      fullPath: '/transportes'
      preLoaderRoute: typeof TransportesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solicitar': {
      id: '/solicitar'
      path: '/solicitar'
      fullPath: '/solicitar'
      preLoaderRoute: typeof SolicitarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motoristas': {
      id: '/motoristas'
      path: '/motoristas'
      fullPath: '/motoristas'
      preLoaderRoute: typeof MotoristasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MotoristasRoute: MotoristasRoute,
  PerfilRoute: PerfilRoute,
  SolicitarRoute: SolicitarRoute,
  TransportesRoute: TransportesRoute,
  ValidacaoRoute: ValidacaoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
